name: Discord Notifications

on:
  pull_request:
    types: [opened, reopened, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]
  push:
    branches:
      - main

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Notification
        if: github.event_name == 'pull_request'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Pull Request ${{ github.event.action }}"
          description: |
            Repository: ${{ github.repository }}
            PR Title: ${{ github.event.pull_request.title }}
            PR Link: ${{ github.event.pull_request.html_url }}
          color: 5814783
          username: ${{ github.event.pull_request.user.login }}
          avatar_url: ${{ github.event.pull_request.user.avatar_url }}

      - name: Pull Request Review Notification
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'submitted'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New PR Review"
          description: |
            Repository: ${{ github.repository }}
            PR: ${{ github.event.pull_request.title }}
            Review State: ${{ github.event.review.state }}
            Review Body: ${{ github.event.review.body }}
            Review Link: ${{ github.event.review.html_url }}
          color: 3066993
          username: ${{ github.event.review.user.login }}
          avatar_url: ${{ github.event.review.user.avatar_url }}

      - name: Issue Comment / PR Comment Notification
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New Comment on PR"
          description: |
            Repository: ${{ github.repository }}
            PR: ${{ github.event.issue.title }}
            Comment: ${{ github.event.comment.body }}
            Link: ${{ github.event.comment.html_url }}
          color: 3066993
          username: ${{ github.event.comment.user.login }}
          avatar_url: ${{ github.event.comment.user.avatar_url }}

      - name: Main Branch Push Notification
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New Commit to Main Branch"
          description: |
            Repository: ${{ github.repository }}
            Commit Message: ${{ github.event.commits[0].message }}
            Committer: ${{ github.event.commits[0].author.name }}
          color: 15158332
